### Test du controller Projects

GET http://localhost:3002/api/projects?page=1
Accept: application/json

### Obtenir tous les projets sans pagination
GET http://localhost:3002/api/projects

### Obtenir un projet par slug
GET http://localhost:3002/api/projects/reforestation-bretagne
Accept: application/json

### Obtenir les arbres d'un projet par slug
GET http://localhost:3002/api/projects/reforestation-bretagne/trees?page=1
Accept: application/json
