### Obtenir tous les projets
GET http://localhost:3001/api/projects

### Obtenir tous les arbres
GET http://localhost:3001/api/trees?page=1

###

### Obtenir les arbres d'un projet
GET http://localhost:3001/api/projects/slug-du-projet/trees?page=1


### test
GET http://localhost:3001/projects?page=1


### test de l'api
GET http://localhost:3001/

